config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users
  resources :games
  resources :events, only: [:index, :create, :show, :new] do
    collection do
      post 'results'
    end
  end
  get "user_profile", to: 'users#user_profile'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :games, only: [:index, :show, :update]
      resources :categories, only: [:index, :show]
      resources :users, only: [:index] 
      get 'users/current/following', to: 'users#following'
      post 'users/current/following', to: 'users#follow'
      post 'users/current/unfollow', to: 'users#unfollow'
      resources :events, only: [:index]
      get '/users/current', to: 'users#current'
      resources :invitations, only: [:index] do
        collection do
          post 'accept'
          post 'decline'
        end
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :game
  belongs_to :owner, class_name: 'User'

  has_many :invitations
  has_many :users, through: :invitations
  has_many :achivements

  validates :title, length: { minimum: 2, maximum: 35 }, presence: true
  validates :description, length: { maximum: 500 }, presence: true
  validates :game, presence: true
  validates :event_time, presence: true
  validates :event_date, presence: true
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApiController
  def index
    @events = Event.all
  end

  def event_user
    @event = Event.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show]
  before_action :authenticate_user!

  def index
    @events = Event.where(owner: current_user.id).order('created_at DESC')
  end

  def create
    @game = current_user.games.pluck(:title)
    @event = current_user.events.build(event_params)
    if @event.save
      params[:event][:achivements]&.map do |achivement|
        @event.achivements.create(name: achivement)
      end
      redirect_to @event
    else
      render 'new'
    end
  end

  def new
    @event = current_user.events.build
    @users = User.all
    @game = current_user.games.pluck(:title)
  end

  def results
    User.find(params[:first_id]).first!
    User.find(params[:second_id]).second!
    User.find(params[:third_id]).third!
    @event = Event.find(params[:event_id])
    @event.update(finalised: true)
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :event_time, :event_date, :private, user_ids: []).
      merge(owner_id: current_user.id, game_id: Game.find_by(title: params[:event][:game])&.id)
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
%main.add-event-form
    = form_for @event do |form|
        %h1.events-header= "Add event:"
        .row.justify-content-center
            .col-md-9
                .form-group.row.event_title
                    .col-md-6.col_en
                        = form.label :title 
                    .col-md-6.col_event_title
                        = form.text_field :title
                .form-group.row.event_desc
                    .col-md-6.col_ed
                        = form.label :description
                    .col-md-6.col_event_desc
                        = form.text_area :description
                .form-group.row.event_t
                    .col-md-6.col_et
                        = form.label :event_time
                    .col-md-6.col_event_t
                        = form.time_field :event_time
                .form-group.row.event_d
                    .col-md-6.col_dd
                        = form.label :event_date
                    .col-md-6.col_event_d
                        = form.date_field :event_date
                .form-group.row.event_game
                    .col-md-6.col_eg
                        = form.label :game
                    .col-md-6.col_event_game
                        = form.select(:game, options_for_select(@game))
                .form-group.row.players.users-list
                    = javascript_pack_tag 'usersEventList'
                .form-group.row.achivements-list
                    = javascript_pack_tag 'achivementsList'
                .form-group.row.event_private
                    .col-md-6
                        = form.label :private
                    .col-md-6.colprivate
                        = form.check_box :private
                
                .form-group.row.add_btn
                    .col-md-6.col_merde
                        .add_event  
                            %button.bg-transparent.add-event-button-submit{type: "submit", style: "border: none"}
                                = form.submit 'Add Event'
               
                   

app/views/events/edit.html.haml
.show-event-page
  .row.justify-content-center
    .show-event-page-title
      %h3.show-labelt= "Title:"  
      %p.event-title= @event.title
    .show-event-page-users
      %h3.show-labelp= "Players:"
      %div.players
        = javascript_pack_tag 'addPoints'

            

app/views/events/index.html.haml
.add-event-button-wrapper
    = button_to 'ADD EVENT', new_event_path, class: "add-event-button", method: :get
.events-list-wrapper
    .events-list
        #events
            = javascript_pack_tag 'eventsList'
            

app/views/events/new.html.haml
=render 'form'

app/views/events/show.html.haml
.show-event-page
  .row.justify-content-center
    - if (@event.event_time < Time.now && @event.event_date < Date.today && !@event.users.empty? && !@event.finalised && @event.owner == current_user)
      .show-event-page-users
        %h3.show-labelp.results= "Results:"
        = form_with url: results_events_path do |form|
          = hidden_field_tag "event_id", @event.id
          .form-group.row#cat
            .col-md-6 
              = form.label :first
            .col-md-6#col_cat
              = form.select :first_id, @event.users.collect { |user| [user.nick, user.id] }
          .form-group.row#cat
            .col-md-6 
              = form.label :second
            .col-md-6#col_cat
              = form.select :second_id, @event.users.collect { |user| [user.nick, user.id] }
          .form-group.row#cat
            .col-md-6 
              = form.label :third
            .col-md-6#col_cat
              = form.select :third_id, @event.users.collect { |user| [user.nick, user.id] }
          .form-group.row
            .col.text-center
              = form.submit 'Save results', class: 'winners-button'
    .show-event-page-title
      %h3.show-labelt= "Title:"  
      %p.event-title= @event.title
    .show-event-page-description
      %h3.show-labeld= "Details:"
      %p.event-desc= @event.description
    .show-event-page-time
      %h3.show-labeldt= "Date:"
      %div.event-date= @event.event_date
      %div.event-date= @event.event_time.to_formatted_s(:time)
    .show-event-page-game
      %h3.show-labelg= "Game:"
      %div.event-game= @event.game.title
    - unless @event.invitations.where(user_id: current_user.id).empty?
      .show-event-page-users
        %h3.show-labelp= "Change status:"
        .row.status-wrapper
          .col.text-center
            = button_to 'Accept', accept_api_v1_invitations_path, form_class: 'accept', method: :post, params: {id: Invitation.find_by(event_id: @event.id, user_id: current_user.id)}
          .col.text-center
            = button_to 'Decline', decline_api_v1_invitations_path, form_class: 'decline', method: :post, params: {id: Invitation.find_by(event_id: @event.id, user_id: current_user.id)}
    .show-event-page-users
      %h3.show-labelp= "Players:"
      %h5= "Accepted:"
      - @event.invitations.accepted.each do |invite|
        %div.event-players
          = invite.user.nick
      %h5= "Pending:"
      - @event.invitations.pending.each do |invite|
        %div.event-players
          = invite.user.nick
      %h5= "Declined:"
      - @event.invitations.declined.each do |invite|
        %div.event-players
          = invite.user.nick
    .show-event-page-achivements
      %h3.show-labela= "Achievements:"
      - @event.achivements.each do |achivement|
        %div.event-achivements= achivement.name