config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users
  resources :games
  resources :events, only: [:index, :create, :show, :new] do
    collection do
      post 'results'
    end
  end
  get "user_profile", to: 'users#user_profile'

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :games, only: [:index, :show, :update]
      resources :categories, only: [:index, :show]
      resources :users, only: [:index] 
      get 'users/current/following', to: 'users#following'
      post 'users/current/following', to: 'users#follow'
      post 'users/current/unfollow', to: 'users#unfollow'
      resources :events, only: [:index]
      get '/users/current', to: 'users#current'
      resources :invitations, only: [:index] do
        collection do
          post 'accept'
          post 'decline'
        end
      end
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/game.rb
class Game < ApplicationRecord
  has_many_attached :pictures
  has_one_attached :game_guide
  belongs_to :category
  belongs_to :user
  has_many :events
  has_many :ratings, foreign_key: 'rated_game_id'
  has_many :rating_users, through: :ratings, class_name: 'User', foreign_key: 'rating_user_id'

  validates :title, presence: true, length: { maximum: 35 }
  validates :description, presence: true, length: { maximum: 255 }
  validate :pictures_amount_ng_than_five
  validate :pictures_extensions
  validate :guide_extension

  private

  def pictures_extensions
    pictures.each do |picture|
      unless picture.content_type.in?(%w[image/jpeg image/png])
        picture.purge
        errors.add(:pictures, 'must be a JPG or a PNG file.')
      end
    end
  end

  def guide_extension
    return unless game_guide.attached? && !game_guide.content_type.in?(%w[application/pdf application/msdoc])

    game_guide.purge
    errors.add(:game_guide, 'must be a PDF or DOC file.')
  end

  def pictures_amount_ng_than_five
    return unless pictures.attachments.size > 5

    pictures.purge
    errors.add(:pictures, 'can not be more than 5.')
  end
end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < ApiController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    game = Game.find(params[:id])
    rating = Rating.find_or_create_by(rated_game_id: game.id, rating_user_id: current_user.id)
    return render json: { errors: rating.errors.full_messages }, status: :unprocessable_entity unless rating.
      update(score: params[:rating])

    return render json: { errors: game.errors.full_messages }, status: :unprocessable_entity unless game.
      update(global_rating: Rating.where(rated_game_id: game.id).average(:score).to_i)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :handle_record_not_found

  def new
    @game = Game.new
  end

  def index; end

  def show
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(game_params)
    return render('new') unless @game.save

    redirect_to games_path
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    return render('edit') unless @game.update_attributes(game_params)

    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:title, :description, :global_rating, :game_guide, :category_id, pictures: []).
      merge(user_id: current_user.id)
  end

  def handle_record_not_found
    redirect_to games_path
  end
end

app/views/games/_errors.haml
- if @game.errors.any?
    .notice
        .putain
            %p.errtitle The form contains #{pluralize(@game.errors.count, "error")}
            %ul
                - @game.errors.full_messages.each do |error_message|
                    %li= error_message

app/views/games/_form.haml
= form_for @game do |form|
    .cotainer
        .row.justify-content-center
            .col-md-8
                .card.bg-transparent#menu_card
                    .card-body.container
             
                        .form-group.row#name
                            .col-md-6#col_n
                                = form.label :title
                            .col-md-6#col_name
                                = form.text_field :title
                        .form-group.row#desc
                            .col-md-6
                                = form.label :description
                            .col-md-6#col_desc
                                = form.text_area :description
                        .form-group.row#pic
                            .col-md-6
                                = form.label :pictures
                            .col-md-6#col_pic
                                =form.file_field :pictures, multiple: true
                        .form-group.row#guide
                            .col-md-6
                                = form.label :game_guide
                            .col-md-6#col_guide
                                = form.file_field :game_guide
                        .form-group.row#cat
                            .col-md-6 
                                = form.label :category
                            .col-md-6#col_cat
                                = form.select :category_id, Category.all.collect { |category| [category.name, category.id] }
                        .form-group.row#add_btn
                            .col-md-6.offset-md-4
                                .add_button  
                                    %button.btn.bg-transparent{type: "submit"}
                                        = form.submit 'Add to my collection'

app/views/games/edit.html.haml
= render partial: 'games/errors', locals: { game: @game }

= render partial: 'games/form', locals: { game: @game }

app/views/games/index.html.haml
.new-game-button-wrapper
    = button_to 'ADD GAME', new_game_path, method: :get, class: 'new-game-button'
.games-list-wrapper
    .games-list
= javascript_pack_tag 'gamesList'

app/views/games/new.html.haml
= render partial: 'games/errors', locals: { game: @game }

= render partial: "games/form", locals: {game: @game}

app/views/games/show.html.haml
.games-form
    = form_for @game do |form|
        
        .row.justify-content-center
            .col-md-8
                .form-group.row.game_name
                    .col-md-6.col_gn
                        Title: 
                    .col-md-6.col_game_name
                        #{@game.title}
                .form-group.row.game_desc
                    .col-md-6.col_gd
                        Description: 
                    .col-md-6.col_game_desc
                        #{@game.description}
                .form-group.row.game_cat
                    .col-md-6.col_gc
                        Category: 
                    .col-md-6.col_game_cat
                        #{@game.category.name}
                .form-group.row.game_guide
                    .col-md-6.col_gg
                        Guide:
                    .col-md-6.col_game_guide
                        - if @game.game_guide.attached?
                            = link_to @game.game_guide.filename, url_for(@game.game_guide), target: '_blank' 
                .form-group.row.game_pic
                    .col-md-6.col_num    
                        Owned pictures: 
                    .col-md-6.col_game_num
                        #{@game.pictures.count}
                .form-group.row.img_show        
                    .pic_display                
                        - @game.pictures.each do |picture|
                            %img.pic(src="#{Rails.application.routes.url_helpers.rails_blob_path(picture, only_path: true)}" alt="test")